Traffic Monitor Integration Test Framework
apache/trafficcontrol pull request #3707
Opened 2019-07-01 14:38 UTC by rob05c

Adds a Traffic Monitor Integration Test Framework.

WIP, but making a draft for input. It needs some cleanup, but it works, and has a few tests. Instructions are in the README, let me know if you have trouble getting it to work.

Also adds a Go client for the Monitor (because it needed it).

Comments welcome.

## What does this PR (Pull Request) do?

- [ ] This PR fixes #REPLACE_ME OR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Documentation
- Grove
- Traffic Control Client 
- Traffic Monitor
- Traffic Ops
- Traffic Ops ORT
- Traffic Portal
- Traffic Router
- Traffic Stats
- Traffic Vault

## What is the best way to verify this PR?

## If this is a bug fix, what versions of Traffic Ops are affected?

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [ ] This PR includes any and all required license headers
- [ ] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [ ] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

2019-07-01 15:01 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3918/
Test FAILed.

2020-09-25 20:31 UTC, rob05c commented
Rebased, removed draft/WIP. I haven't had time to do more with this, but it basically worked. I don't think there's a reason not to merge it, if anyone wants to use and extend it for Traffic Monitor Integration Testing.

2020-09-25 21:54 UTC, zrhoffman requested changes

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/config/config.go
> +			return Config{}, fmt.Errorf("Reading CDN conf '%s': %v", confPath, err)
*Reading* should not be capitalized

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/config/config.go
> +		fmt.Errorf("cannot parse config: %v\n", err)
Is this error meant to be printed?

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/traffic_monitor_test.go
> +	// }
This is all commented out because it's still *todo*, right? Could we get a `TODO` comment about this code block?

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tools/testcaches/fakesrvr/cmd.go
> +		fakeSrvrDataThs.Set(fakesrvrdata.ThsT(srvr))
This can be just

```go
fakeSrvrDataThs.Set(srvr)
```

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tools/testcaches/fakesrvr/cmd.go
> +		fakeSrvrDataThs.Set(fakesrvrdata.ThsT(srvr))
This too can be

```go
fakeSrvrDataThs.Set(srvr)
```

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tools/testcaches/fakesrvr/cmd.go
> +		fakeSrvrDataThs.Set(fakesrvrdata.ThsT(srvr))
Another `fakeSrvrDataThs.Set(srvr)` candidate

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tools/testcaches/fakesrvr/cmd.go
> +		fakeSrvrDataThs.Set(fakesrvrdata.ThsT(srvr))
`fakeSrvrDataThs.Set(srvr)` can be here

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tools/testcaches/fakesrvr/server.go
> +				delayMS += uint64(rand.Int63n(int64((maxDelayMS - minDelayMS))))
Redundant parenthesis here

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/Dockerfile_run.sh
> +    "ipNetmask": "255.255.255.0",
After #4700, this part looks like

```json
      "interfaces": [
        {
          "ipAddresses": [
            {
              "address": "172.16.239.6",
              "gateway": "172.16.239.1",
              "serviceAddress": true
            },
            {
              "address": "fc01:9400:1000:8::6",
              "gateway": "fc01:9400:1000:8::1",
              "serviceAddress": true
            }
          ],
          "maxBandwidth": null,
          "monitor": true,
          "mtu": 1500,
          "name": "eth0"
        }
      ],
```

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/Dockerfile_run.sh
> +	curl -Lvsk ${TESTTO_URI}/api/1.2/cdns/fake/configs/monitoring.json -X POST -d '
As with the rest of the API v2.0 routes, this has become `cdns/fake/configs/monitoring`, `json` suffix no longer supported

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/README.md
> +(cd tests/integration && go test -c -o traffic_monitor_integration_test)
When I run the docker-compose command to start the test,

```shell
docker-compose -p tmi --project-directory . -f tests/integration/docker-compose.yml run tmintegrationtest
```

I indefinitely get

```
Waiting for Traffic Ops to return a 200 OK
```

Looking at the `testto` container, it says

```logs
[user@computer traffic_monitor]$ 3 tmi --project-directory . -f tests/integration/docker-compose.yml logs -f testto
Attaching to tmi_testto_1
testto_1             | testto: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by testto)
tmi_testto_1 exited with code 1
```

So the instructions should have you build with `CGO_ENABLED=0` (and `GOOS=linux`).

2020-09-25 21:54 UTC, zrhoffman commented on traffic_monitor/tests/integration/README.md
> +sudo docker-compose -p tmi --project-directory . -f tests/integration/docker-compose.yml run tmintegrationtest
After resolving the above linking error, rebuilding the images, and re-running, I get unmarshalling errors like

```json
{"error": "unmarshalling posted body: json: cannot unmarshal bool into Go struct field CRConfigDeliveryService.deliveryServices.anonymousBlockingEnabled of type string"}
```

It eventually says

```
Error communicating with Monitor 'http://trafficmonitor' - didn't return a 200 OK in 30s
```

<details><summary>Full <code>tmintegrationtest</code> logs are here (click to expand)</summary>

```
< HTTP/1.1 200 OK
* About to connect() to testto port 80 (#0)
*   Trying 172.23.0.3...
* Connected to testto (172.23.0.3) port 80 (#0)
> POST /api/1.2/cdns/fake/snapshot HTTP/1.1
> User-Agent: curl/7.29.0
> Host: testto
> Accept: */*
> Content-Length: 3756
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Date: Fri, 25 Sep 2020 21:32:19 GMT
< Content-Length: 169
< Content-Type: text/plain; charset=utf-8
* HTTP error before end of send, stop sending
<
* Closing connection 0
{"error": "unmarshalling posted body: json: cannot unmarshal bool into Go struct field CRConfigDeliveryService.deliveryServices.anonymousBlockingEnabled of type string"}* About to connect() to testto port 80 (#0)
*   Trying 172.23.0.3...
* Connected to testto (172.23.0.3) port 80 (#0)
> POST /api/1.2/cdns/fake/configs/monitoring.json HTTP/1.1
> User-Agent: curl/7.29.0
> Host: testto
> Accept: */*
> Content-Length: 2308
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Date: Fri, 25 Sep 2020 21:32:19 GMT
< Content-Length: 167
< Content-Type: text/plain; charset=utf-8
* HTTP error before end of send, stop sending
<
* Closing connection 0
{"error": "unmarshalling posted body: json: cannot unmarshal object into Go struct field TrafficServer.trafficServers.deliveryServices of type []tc.tsdeliveryService"}* About to connect() to testto port 80 (#0)
*   Trying 172.23.0.3...
* Connected to testto (172.23.0.3) port 80 (#0)
> POST /api/1.2/servers HTTP/1.1
> User-Agent: curl/7.29.0
> Host: testto
> Accept: */*
> Content-Length: 1135
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 204 No Content
< Date: Fri, 25 Sep 2020 21:32:19 GMT
<
* Connection #0 to host testto left intact


testto:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3877    0  3877    0     0   657k      0 --:--:-- --:--:-- --:--:--  757k
{"response":{
  "config": {
    "api.cache-control.max_age": "30",
    "consistent.dns.routing": "true",
    "coveragezone.polling.interval": "30",


testcaches:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{ 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
1  "ats": {
0    "plugin.remap_stats.num7.example.net.in_bytes": 2,
0    "plugin.remap_stats.num7.example.net.out_bytes": 2,
     "plugin.remap_stats.num7.example.net.status_2xx": 1,
34955    0 34955    0     0  4648k      0 --:--:-- --:--:-- --:--:-- 4876k
(23) Failed writing body


traffic_monitor:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6522<!DOCTYPE html>0     0      0      0 --:--:-- --:--:-- --:--:--     0

 <!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
0  6522    0     0  1159k      0 --:--:-- --:--:-- --:--:-- 1273k
(23) Failed writing body
DEBUG traffic_monitor_integration starting

Error communicating with Monitor 'http://trafficmonitor' - didn't return a 200 OK in 30s
```
</details>

Looking at the logs of the `trafficmonitor` container, it doen't seem to get past

```go
ERROR: datareq.go:152: 2020-09-25T21:32:38.143874758Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
```

although there are other errors in there too, like

```go
trafficmonitor_1     | ERROR: monitorconfig.go:346: 2020-09-25T21:32:33.530687712Z: Failed to parse polling strings for cache server 'server0': no service addresses found
trafficmonitor_1     | ERROR: monitorconfig.go:346: 2020-09-25T21:32:33.530798803Z: Failed to parse polling strings for cache server 'server1': no service addresses found
```

<details><summary>Full <code>trafficmonitor</code> container logs are here (click to expand)</summary>

```go
Attaching to tmi_trafficmonitor_1
trafficmonitor_1     | Failed to get D-Bus connection: Operation not permitted
trafficmonitor_1     | /etc/init.d/traffic_monitor: line 41: /etc/sysconfig/network: No such file or directory
trafficmonitor_1     | Starting traffic_monitor: 
trafficmonitor_1     | ERROR: opsconfig.go:77: 2020-09-25T21:32:18.530467624Z: OpsConfigManager: getting CDN name from Traffic Ops, using config CDN 'nocdn': getting monitor CDN: no server 'trafficmonitor' found in Traffic Ops
trafficmonitor_1     | 
trafficmonitor_1     | ERROR: opsconfig.go:77: 2020-09-25T21:32:18.538113399Z: OpsConfigManager: Error getting Traffic Ops data: Error getting CRconfig from Traffic Ops: invalid CRConfig: CRConfig.Stats.CDN missing
trafficmonitor_1     | 
trafficmonitor_1     | ERROR: opsconfig.go:205: 2020-09-25T21:32:18.538157142Z: retrying in 100ms
trafficmonitor_1     | ERROR: opsconfig.go:77: 2020-09-25T21:32:18.638750564Z: OpsConfigManager: Error getting Traffic Ops data: Error getting CRconfig from Traffic Ops: invalid CRConfig: CRConfig.Stats.CDN missing
trafficmonitor_1     | 
trafficmonitor_1     | ERROR: opsconfig.go:205: 2020-09-25T21:32:18.638781915Z: retrying in 248.612746ms
trafficmonitor_1     | ERROR: opsconfig.go:77: 2020-09-25T21:32:18.888066827Z: OpsConfigManager: Error getting Traffic Ops data: Error getting CRconfig from Traffic Ops: invalid CRConfig: CRConfig.Stats.CDN missing
trafficmonitor_1     | 
trafficmonitor_1     | ERROR: opsconfig.go:205: 2020-09-25T21:32:18.888119514Z: retrying in 642.263625ms
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:20.102734056Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:21.1049107Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:22.107247084Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:23.109295834Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:24.111672602Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:25.113719758Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:26.115813436Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:27.118294393Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:28.120237324Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:29.122398443Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficmonitor_1     | ERROR: datareq.go:152: 2020-09-25T21:32:30.123841491Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
trafficm [...]

2021-05-10 19:35 UTC, rob05c commented
> @rob05c can this be closed in favor of #5817

Once it's merged, yeah. I'd prefer to keep it open until then so we don't lose track of it, just in case something happens to 5817 and it's closed or doesn't get merged or something

2021-06-01 16:05 UTC, zrhoffman commented
#5817 is based off of #3707 and is merged.

2021-06-01 16:05 UTC, closed without merging