Traffic Portal objects blueprint
apache/trafficcontrol pull request #4986
Opened 2020-08-25 16:40 UTC by ocket8888

## What does this PR (Pull Request) do?
- [x] This PR is not related to any Issue

This PR adds a blueprint for "breaking out" Traffic Portals into their own API object, out of the generic "server" object.

## Which Traffic Control components are affected by this PR?
None

## What is the best way to verify this PR?
Read the blueprint.

## The following criteria are ALL met by this PR
- [x] Tests are unnecessary for blueprints
- [x] Documentation is unnecessary for blueprints
- [x] An update to CHANGELOG.md is not necessary for blueprints
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

2020-09-16 23:26 UTC, jhg03a requested changes

2020-09-16 23:26 UTC, jhg03a commented on blueprints/traffic.portal.objects.md
> +there aren't any that look specifically for Traffic Portal servers).
They exist.

2020-09-16 23:26 UTC, jhg03a commented on blueprints/traffic.portal.objects.md
> +the generic `servers` table should be left up to operators' discretion. The
The existing server object must not be removed or more of its functions must be added to this new object.  TO is the system of record for all infrastructure in ATC.  All the concepts of how operators can access it such as OOB login info or management IPs must be preserved.

2020-09-16 23:26 UTC, jhg03a commented on blueprints/traffic.portal.objects.md
> +This property uniquely identifies a Traffic Portal, and must therefore
Are you also attempting to cover the use case of a LB sitting in front of multiple TP instances?

2020-09-16 23:40 UTC, rob05c commented on blueprints/traffic.portal.objects.md
> +interface TrafficPortal {
This is missing a lot of Asset data about the physical server.
I've said for years that IMO Traffic Ops shouldn't be used for Asset Management. But it's simply a fact that it's designed and used for that today.

A lot of Server fields this removes are cache-specific, but a lot are Asset data. Like the netmask, gateway, ILO fields, physLocation, rack. That's all Asset data people are using to track server machines today, that has to be stored somewhere.

Unless there's a concrete proposal that Traffic Control / Traffic Ops move away from Asset Management, and Users (including us) will be required to migrate their data into new Asset Management systems?

Is the intention to propose and require that?

If not, we need to identify and add the Asset-related fields (the ones I mention aren't exhaustive). Ideally in a shared DB table for normalization.

2020-09-17 00:15 UTC, ocket8888 commented
Thanks for the reviews, but this was just an example for a proposal on the mailing list. A proposal which appears to be rejected - at least in its current form. This blueprint, therefore, no longer serves any purpose. I had just forgotten to close it.

2020-09-17 00:15 UTC, closed without merging

2020-09-17 00:22 UTC, jhg03a commented on blueprints/traffic.portal.objects.md
> +This boolean value indicates whether or not this Traffic Portal is online and
This is a functionality reduction from today where we can have TP in custom statuses that match server lifecycle.