Fix TO to generate monitoring if no snapshot
apache/trafficcontrol pull request #5066
Opened 2020-09-23 17:58 UTC by rob05c

Fixes TO to generate monitoring if no snapshot.
This fixes a critical issue of upgrading to 4.x breaking production CDNs until a Snapshot is done.

Includes tests.
Includes changelog.
No docs, no interface change.

- [x] This PR does part of #5005 but that issue requires the 4.x Backport as well

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
Request the /monitoring endpoint on a TO CDN with no CRConfig/Monitoring Snapshot, verify endpoint returns full monitoring not `""` or `{}`. Verify TO logs an Error that a snapshot needs to be performed.

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 4.x

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

2020-10-05 14:29 UTC, smalenfant requested changes
I upgrade a 4.1 branch that had this code in. Once I upgraded TO, the returned value for the API call was still `{}`

```
TASK [Get Monitoring.json] *************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "monitoring": {
        "access_control_allow_credentials": "true", 
        "access_control_allow_headers": "Origin, X-Requested-With, Content-Type, Accept, Set-Cookie, Cookie", 
        "access_control_allow_methods": "POST,GET,OPTIONS,PUT,DELETE", 
        "access_control_allow_origin": "*", 
        "changed": false, 
        "connection": "close", 
        "content": "{\"response\":{}}", 
        "content_length": "15", 
        "content_type": "application/json", 
        "cookies": {
            "mojolicious": "eyJhdXRoX2RhdGEiOiJjaHMiLCJleHBpcmVzIjoxNjAxOTExNTQwLCJieSI6InRyYWZmaWNjb250cm9sLWdvLXRvY29va2llIn0--158c900af6b3e71ea8355cf22a71c04dc4c0b8ce"
        }, 
        "cookies_string": "mojolicious=eyJhdXRoX2RhdGEiOiJjaHMiLCJleHBpcmVzIjoxNjAxOTExNTQwLCJieSI6InRyYWZmaWNjb250cm9sLWdvLXRvY29va2llIn0--158c900af6b3e71ea8355cf22a71c04dc4c0b8ce", 
        "date": "Mon, 05 Oct 2020 14:25:40 GMT", 
        "elapsed": 0, 
        "failed": false, 
        "json": {
            "response": {}
        }, 
        "msg": "OK (15 bytes)", 
        "redirected": false, 
        "set_cookie": "mojolicious=eyJhdXRoX2RhdGEiOiJjaHMiLCJleHBpcmVzIjoxNjAxOTExNTQwLCJieSI6InRyYWZmaWNjb250cm9sLWdvLXRvY29va2llIn0--158c900af6b3e71ea8355cf22a71c04dc4c0b8ce; Path=/; Expires=Mon, 05 Oct 2020 15:25:40 GMT; Max-Age=3600; HttpOnly", 
        "status": 200, 
        "url": "https://cdn1cdkafka0001.coxlab.net:8443/api/1.5/cdns/cdn5/configs/monitoring.json", 
        "vary": "Accept-Encoding", 
        "whole_content_sha512": "fadAH7v4t4+B05+YRoSxSAo8Wjhfdu9CGGY2vUyRUZkL+xblR4aXDthsWPAaYjNLlANfQaAExyGT4qWU5VoVcg==", 
        "x_server_name": "traffic_ops_golang/"
    }
}
```

2020-10-05 16:26 UTC, smalenfant approved these changes
Ran the correct version and worked as intended. Thanks @rob05c

2020-10-06 16:10 UTC, rawlinp commented
@rob05c there is a merge conflict in the changelog

2020-10-06 20:19 UTC, rob05c commented
Fixed

2020-10-06 21:53 UTC, merged