Add t3c-determine-restart
apache/trafficcontrol pull request #5281
Opened 2020-11-13 17:21 UTC by rob05c

## What does this PR (Pull Request) do?

- [ ] This PR fixes #REPLACE_ME OR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Documentation
- Grove
- Traffic Control Client 
- Traffic Monitor
- Traffic Ops
- Traffic Ops ORT
- Traffic Portal
- Traffic Router
- Traffic Stats
- Traffic Vault
- CI tests

## What is the best way to verify this PR?

## If this is a bug fix, what versions of Traffic Control are affected?

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [ ] This PR includes any and all required license headers
- [ ] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

2021-05-13 20:37 UTC, ezelkow1 approved these changes
Looks good, tested on my lab cache with staging and updated when appropriate and when not

2021-05-13 23:38 UTC, zrhoffman requested changes

2021-05-13 23:38 UTC, zrhoffman commented on cache-config/t3c-check/t3c-check.go
> +	"reload": struct{}{},
This can be just
```go
	"refs":   {},
	"reload": {},
```

2021-05-17 14:34 UTC, rob05c commented on cache-config/t3c-apply/config/config.go
>  	"github.com/pborman/getopt/v2"
Changed

2021-05-17 14:36 UTC, rob05c commented on cache-config/t3c-check/t3c-check.go
> +	"reload": struct{}{},
Changed

2021-05-17 15:23 UTC, zrhoffman approved these changes
Look's good! The CI seems backed up for the apache org right now, but it passed on [your fork](https://github.com/rob05c/trafficcontrol/actions?query=branch:ort-restart-determiner). Merging...

2021-05-17 15:23 UTC, merged

2021-05-17 18:46 UTC, zrhoffman reviewed
There are still references to `t3c-verify` in some files.

https://github.com/apache/trafficcontrol/blob/2637e1c2eb91761002a482f7adeb95bbeb829869/cache-config/t3c-check-refs/README.md#L26
https://github.com/apache/trafficcontrol/blob/2637e1c2eb91761002a482f7adeb95bbeb829869/cache-config/t3c/README.md#L34
https://github.com/apache/trafficcontrol/blob/2637e1c2eb91761002a482f7adeb95bbeb829869/cache-config/t3c/t3c.go#L98

2021-05-17 21:02 UTC, rob05c commented
> There are still references to t3c-verify in some files.
Fixed in https://github.com/apache/trafficcontrol/pull/5852