Return the correct error while trying to update the root tenant
apache/trafficcontrol pull request #5397
Opened 2020-12-30 00:58 UTC by srijeet0406

## What does this PR (Pull Request) do?

- [x] This PR fixes #5396  

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Ops

## What is the best way to verify this PR?

Go to traffic portal and try to update the `root` tenant
You will receive a `400 Bad Request` error with the correct error msg.

## If this is a bug fix, what versions of Traffic Control are affected?

- master

## The following criteria are ALL met by this PR

- [x] This PR includes tests 
- [x] This PR includes documentation 
- [x] This PR includes an update to CHANGELOG.md 
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

2021-01-05 18:57 UTC, zrhoffman requested changes

2021-01-05 18:57 UTC, zrhoffman commented on traffic_ops/traffic_ops_golang/apitenant/tenant.go
> +		// If its the rot tenant, dont check for parent
* its
* rot
* dont

2021-01-05 18:57 UTC, zrhoffman commented on traffic_ops/traffic_ops_golang/apitenant/tenant.go
> +		return errors.New("cannot update the root tenant"), nil, http.StatusBadRequest
400-level errors should include a description of why the server rejected the request.

2021-01-05 19:01 UTC, zrhoffman commented
> This PR includes documentation

I can't find the documentation

2021-01-06 05:20 UTC, srijeet0406 commented
> > This PR includes documentation
> 
> I can't find the documentation

Fixed

2021-01-06 15:57 UTC, zrhoffman requested changes

2021-01-06 20:37 UTC, merged

2021-01-06 20:37 UTC, zrhoffman approved these changes