Fixed GET api/3.1/cdns/routing endpoint
apache/trafficcontrol pull request #5709
Opened 2021-04-02 18:31 UTC by rimashah25

## What does this PR (Pull Request) do?

- [x] This PR fixes #REPLACE_ME OR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

## If this is a bug fix, what versions of Traffic Control are affected?

- 5.1.1
- master (7f5c7be)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

2021-04-02 19:56 UTC, rawlinp commented on traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/StatTracker.java
>  	private int totalDsMissCount = 0;
We might as well make this a `long` as well just to round them all out.

2021-04-05 19:57 UTC, mattjackson220 approved these changes
Looks good to me! tests pass and it should fix the issue! nice!

2021-04-05 21:47 UTC, zrhoffman requested changes
> Fixed GET api/3.1/cdns/routing endpoint

Since it gets written to the git history, would you please edit the title to describe what issue with the `/api/3.1/cdns/routing` endpoint is fixed by this PR?

2021-04-05 22:17 UTC, rawlinp approved these changes
LGTM once more details are included in the title as @zrhoffman suggests.

2021-04-05 22:26 UTC, zrhoffman approved these changes

2021-04-05 22:26 UTC, merged