Uri Sig Keys in Postgres
apache/trafficcontrol pull request #5814
Opened 2021-05-05 18:55 UTC by mattjackson220

## What does this PR (Pull Request) do?

- [x] This PR fixes is not related to any Issue 
This PR adds support for URI Signing Keys using Postgres as Traffic Vault

## Which Traffic Control components are affected by this PR?

- Traffic Ops
- Traffic Vault

## What is the best way to verify this PR?

Run TO with Postgres as the TV backend
Verify that the API tests work
Verify that GET, POST, PUT, and DELETE work for URI signing keys
Verify that ^ all works for Riak still

## If this is a bug fix, what versions of Traffic Control are affected?

## The following criteria are ALL met by this PR

No doc changes since its just a different backend, no changelog changes since that is covered under the postgres backend line already there.
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

2021-05-05 20:17 UTC, srijeet0406 commented on traffic_ops/v4-client/deliveryservice.go
> +func (to *Session) DeleteDeliveryServiceURISigKeys(dsName string, header http.Header) (tc.Alerts, toclientlib.ReqInf, error) {
Should we change the `dsName` param to `dsXMLId` or something like that, to avoid confusion?

2021-05-05 20:17 UTC, srijeet0406 commented on traffic_ops/v4-client/deliveryservice.go
> +func (to *Session) CreateDeliveryServiceURISigKeys(dsName string, header http.Header, body map[string]tc.URISignerKeyset) (tc.Alerts, toclientlib.ReqInf, error) {
Should we change the `dsName` param to `dsXMLId` or something like that, to avoid confusion?

2021-05-06 23:13 UTC, rawlinp requested changes
Looks good, just some nitpicks on the naming

2021-05-06 23:13 UTC, rawlinp commented on traffic_ops/testing/api/v4/deliveryservices_test.go
> +			CreateTestDeliveryServicesURISigKeys(t)
Colloquially these are known as "URI signing keys" as opposed to "URL sig keys", so we should probably fully spell out `Signing` here just to alleviate some confusion.

2021-05-06 23:13 UTC, rawlinp commented on traffic_ops/traffic_ops_golang/trafficvault/backends/postgres/uri_sig_keys.go
> +func getURISigKeys(xmlID string, tvTx *sqlx.Tx, ctx context.Context) ([]byte, bool, error) {
Colloquially these are known as "URI signing keys" as opposed to "URL sig keys", so we should probably fully spell out `Signing` here just to alleviate some confusion.

2021-05-06 23:13 UTC, rawlinp commented on traffic_ops/traffic_ops_golang/trafficvault/backends/postgres/uri_sig_keys.go
> +func putURISigKeys(xmlID string, tvTx *sqlx.Tx, keys []byte, ctx context.Context) error {
Colloquially these are known as "URI signing keys" as opposed to "URL sig keys", so we should probably fully spell out `Signing` here just to alleviate some confusion.

2021-05-06 23:13 UTC, rawlinp commented on traffic_ops/traffic_ops_golang/trafficvault/backends/postgres/uri_sig_keys.go
> +func deleteURISigKeys(xmlID string, tvTx *sqlx.Tx, ctx context.Context) error {
Colloquially these are known as "URI signing keys" as opposed to "URL sig keys", so we should probably fully spell out `Signing` here just to alleviate some confusion.

2021-05-10 22:12 UTC, merged