update readme for TO on cross compilation
apache/trafficcontrol pull request #6422
Opened 2021-12-12 21:02 UTC by asheikm

<hr>

## Which Traffic Control components are affected by this PR?

- Documentation

## What is the best way to verify this PR?
This PR updates README doc, 

## PR submission checklist
- [x] This PR has documentation

2021-12-14 16:33 UTC, asheikm commented
I tried to cross compile on windows for CentOS x64, hope this instruction would help it ? @zrhoffman pls review

2022-06-08 17:11 UTC, ocket8888 requested changes

2022-06-08 17:11 UTC, ocket8888 commented on traffic_ops/traffic_ops_golang/README.md
> +To cross compile the code in windows to generate binaryt to run on linux, Please replace GOARCH for architecture to build
spelling; "binaryt" -> "binary"

Windows and Linux are proper nouns; need capitalization

Grammar: "Please" should not be capitalized in the middle of the sentence

Grammar and clarity: "..., Please replace GOARCH for architecture to build" -> "..., please run the following command, replacing `GOARCH` with the architecture for which to build." (note ending punctuation).

2022-06-08 17:11 UTC, ocket8888 commented on traffic_ops/traffic_ops_golang/README.md
> +`env GOOS=linux GOARCH=arm64 go build `
This should probably be in a code block like:
~~~markdown
```bash
env GOOS=linux GOARCH=arm64 go build
```
~~~

2022-06-08 17:11 UTC, ocket8888 commented on traffic_ops/traffic_ops_golang/README.md
> +Once binary generated, can be copied into linux machine to run
Linux is a proper noun, needs capitalization.

Grammar: "Once <ins>the</ins> binary <ins>is</ins> generated, <ins>it</ins> can be copied <del>into</del><ins>onto</ins> <ins>a</ins> <del>l</del><ins>L</ins>inux machine to <ins>be</ins> run<ins>.</ins>" (note ending punctuation).

2022-06-09 15:52 UTC, ocket8888 approved these changes

2022-06-09 15:52 UTC, merged