Add the ability to edit and delete existing Jobs to TPv2
apache/trafficcontrol pull request #6453
Opened 2022-01-07 15:30 UTC by ocket8888

Adds to TPv2 the ability to delete and edit existing jobs (jobs can only be edited if they haven't started, only deleted if they either haven't started or have finished).

<hr/>

## Which Traffic Control components are affected by this PR?
- Traffic Portal (experimental v2)

## What is the best way to verify this PR?
Make sure the tests pass, make a Job that will run in the future, edit it, delete it, make a Job that's currently running (only possible though database manipulation or waiting for long periods of time), make sure you can't edit or delete it, make a Job that's finished running (only possible through database manipulation or waiting for long periods of time) and make sure you can't edit it, then delete it.

## PR submission checklist
- [x] This PR has tests
- [ ] This PR has documentation
- [ ] This PR has a CHANGELOG.md entry
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

2022-01-11 21:56 UTC, shamrickus requested changes
Works just some small usability suggestions

2022-01-11 21:59 UTC, ocket8888 commented on experimental/traffic-portal/src/app/core/invalidation-jobs/new-invalidation-job-dialog/new-invalidation-job-dialog.component.ts
>  	/** A subscribable that tracks whether the new job's regexp is valid. */
Why 180? I just picked 178 because it was the median value used in a production environment I surveyed.

2022-01-11 22:02 UTC, shamrickus commented on experimental/traffic-portal/src/app/core/invalidation-jobs/new-invalidation-job-dialog/new-invalidation-job-dialog.component.ts
>  	/** A subscribable that tracks whether the new job's regexp is valid. */
Because I like round numbers, 178 just seemed arbitrary but if there's a reason behind it.

2022-01-11 22:08 UTC, ocket8888 commented on experimental/traffic-portal/src/app/core/invalidation-jobs/invalidation-jobs.component.html
> +			aria-label="edit this content invalidation job"
I don't think so - I don't object, it's just that there's no requirement I can see anywhere in WHATWG or MDN that says they should be capitalized and/or be complete sentences.

2022-01-11 22:17 UTC, shamrickus commented on experimental/traffic-portal/src/app/core/invalidation-jobs/invalidation-jobs.component.html
> +			aria-label="edit this content invalidation job"
I suppose it really doesn't matter for `aria-labels` but for the user I think it makes more sense if the title to be.

2022-01-11 23:36 UTC, ocket8888 commented on experimental/traffic-portal/src/app/core/invalidation-jobs/invalidation-jobs.component.html
> +			aria-label="edit this content invalidation job"
I'll just change them both for consistency

2022-01-12 21:10 UTC, shamrickus approved these changes
LGTM

2022-01-12 21:10 UTC, merged