Fix APIv4 and under DSRs not having Original set on Update DSRs
apache/trafficcontrol pull request #7235
Opened 2022-12-06 19:46 UTC by ocket8888

DSRs in versions earlier than 5.0 should have their requested _and_ original DS's set, but because of a bug in the downgrade process, the original was being discarded. This PR fixes that bug.

<hr/>

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
I added unit test coverage for the case where neither original nor requested should be nil, so it should suffice that the tests pass. But the way this bug was found was because the DSR edit page was busted, so you may want to check that out to make sure it works.   

## If this is a bugfix, which Traffic Control versions contained the bug?
- master

## PR submission checklist
- [x] This PR has tests
- [x] This PR doesn't need documentation
- [x] This PR doesn't need a CHANGELOG.md entry
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

2022-12-07 19:45 UTC, rimashah25 commented
Code LGTM

2022-12-07 20:12 UTC, shamrickus requested changes
Seeing this unrelated error on the page still:
```
Error: [$parse:syntax] [http://errors.angularjs.org/1.8.3/$parse/syntax?p0=%3E&p1=no…UpperCase()%20%2B%20w.substring(1).toLowerCase()).join('%20'](http://errors.angularjs.org/1.8.3/$parse/syntax?p0=%3E&p1=not%20a%20primary%20expression&p2=36&p3=dsCurrent.active.split(%27%20%27).map(w%20%3D%3E%20w%5B0%5D.toUpperCase()%20%2B%20w.substring(1).toLowerCase()).join(%27%20%27)&p4=%3E%20w%5B0%5D.toUpperCase()%20%2B%20w.substring(1).toLowerCase()).join(%27%20%27))
    F https://localhost:60443/resources/assets/js/shared-libs.js?built=1670442061842:194
```
    
Also while your changes technically catches the error, I still think those should be fixed (or at least not pollute the console). Just changing the Content Routing Type causes a dozen of the label not found error.

2022-12-07 22:57 UTC, rimashah25 commented
Tested on local and now I do see the current value populated correctly with old value and new value is seen in the field.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/22248619/206314902-820b55de-7a81-49fd-bb93-f8e05d4bc555.png">

2022-12-07 22:59 UTC, rimashah25 requested changes
Need to fix parse error that @shamrickus commented.

2022-12-08 16:50 UTC, ocket8888 commented
> Also while your changes technically catches the error, I still think those should be fixed (or at least not pollute the console). Just changing the Content Routing Type causes a dozen of the label not found error.

Changing anything will do that, just because it triggers a digest cycle. All of those errors are coming from DSCP labeling, because many DSCPs aren't labeled. Tell me, though, what does a DSCP of 10 mean? According to the "human-friendly" label, it means "10 - AF11". What's that? Our docs don't tell you, there's no tooltip that tells you. Even better, look at a DSCP of 37. What that value means - according to the label - is simply "37 - ". Insightful.

I think these are proprietary labels that have no real meaning for the ATC project, and IMO we'd be better off without them. Numbers is numbers. That would stop the log spam. But that's also unrelated to this PR, could be done at a later date if we don't think it's safe to pull that trigger right now.

2022-12-08 22:11 UTC, merged