Add TPv2 to CDN in a Box
apache/trafficcontrol pull request #7389
Opened 2023-03-08 21:46 UTC by shamrickus

This PR adds TPv2 to CDN in a Box.

This PR fixes #7301. It also updates deprecated nightwatch commands to the recommended form. The `currentUser` service has been moved to `current-user` to be more in-line with convention. It also updates the theme service to use the injected `window` instead of relying on globals. It also fixes the route for server details. Finally the CiaB TP container should now actually output the `traffic_portal.log` by default instead of nothing.
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Portal v2
- CDN in a Box

## What is the best way to verify this PR?
Ensure TPv2 still builds & passes tests. Run CiaB and confirm that it works and TPv2 is now working on port 8443.

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

2023-03-09 15:38 UTC, ocket8888 requested changes

2023-03-09 15:38 UTC, ocket8888 commented on infrastructure/cdn-in-a-box/traffic_portal_v2/run.sh
> +tail -f /var/log/traffic-portal/traffic-portal.log
Instead of starting a daemon and then running another process to watch it, why not just start the process in the foreground?

2023-03-09 15:38 UTC, ocket8888 commented on infrastructure/cdn-in-a-box/traffic_portal_v2/run.sh
> +echo "TO_FQDN: $TO_FQDN"
Are these necessary?

2023-03-09 15:38 UTC, ocket8888 commented on infrastructure/cdn-in-a-box/traffic_portal_v2/run.sh
> +to-enroll "tpv2" ALL || (while true; do echo "enroll failed."; sleep 3 ; done)
I know this is standard in CiaB, but IMO it'd better to just `set -e` and let it fail if it fails.

2023-03-09 15:38 UTC, ocket8888 commented on infrastructure/cdn-in-a-box/traffic_ops/to-access.sh
> +			;;
This section is identical to the one for `tp` - why not just re-use that one?

2023-03-09 15:38 UTC, ocket8888 commented on experimental/traffic-portal/src/app/shared/navigation/tp-sidebar/tp-sidebar.component.html
> +	<mat-sidenav #sidenav mode="side" opened [class.hidden]="hidden">
you don't need to make a CSS class for this, you can just bind to [the HTML `hidden` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden)

2023-03-09 15:47 UTC, shamrickus commented on infrastructure/cdn-in-a-box/traffic_portal_v2/run.sh
> +tail -f /var/log/traffic-portal/traffic-portal.log
To mimic a prod environment. Also this tests the init script, which would _not_ be tested otherwise.

2023-03-14 14:06 UTC, ocket8888 approved these changes

2023-03-14 14:06 UTC, merged

2023-03-14 14:08 UTC, ocket8888 commented on infrastructure/cdn-in-a-box/traffic_portal_v2/run.sh
> +tail -f /var/log/traffic-portal/traffic-portal.log
I still question the value of going to such lengths to mimic real production in an environment that was never meant to be used in production, but now that I have the dev env I have the luxury of not caring what bloat gets added to CiaB, so... ¯\\\_(ツ)\_/¯