add missing lastUpdated prop to PUT /roles
apache/trafficcontrol pull request #7402
Opened 2023-03-14 07:50 UTC by tinfoil-knight

Closes: #7248 

Note: V3 API wasn't updated because it's already deprecated & `GET`, `POST` endpoints for the V3 API don't return the `lastUpdated` property.

<hr/>

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops

## What is the best way to verify this PR?

## If this is a bugfix, which Traffic Control versions contained the bug?

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

2023-03-14 09:30 UTC, tinfoil-knight commented on traffic_ops/traffic_ops_golang/role/roles.go
> +		api.HandleErr(w, r, tx, code, usrErr, fmt.Errorf("updating role and scanning lastUpdated : %w", sysErr))
Note for Reviewer:
Unlike `Query`, the `QueryRow` method returns no error. The chained `Scan` method returns the errors. It is difficult to properly differentiate b/w errors that happened while updating & the ones that occurred while scanning. The error message prefix has therefore been merged together.

Ref: https://jmoiron.github.io/sqlx/#queryrow

2023-03-14 14:34 UTC, ocket8888 requested changes

2023-03-14 14:34 UTC, ocket8888 commented on traffic_ops/traffic_ops_golang/role/roles.go
> +		if err == sql.ErrNoRows {
comparisons with errors should use [`errors.Is`](https://pkg.go.dev/errors#Is) rather than `==`.

2023-03-15 18:42 UTC, ocket8888 approved these changes

2023-03-15 18:42 UTC, merged