Updated Hypnotoad
apache/trafficcontrol pull request #7450
Opened 2023-04-20 14:58 UTC by rimashah25

<hr/>

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops
- Automation (Ansible)

## What is the best way to verify this PR?

## If this is a bugfix, which Traffic Control versions contained the bug?

N/A

## PR submission checklist
- [ ] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

2023-05-10 21:25 UTC, zrhoffman requested changes

2023-05-10 21:25 UTC, zrhoffman commented on traffic_ops/install/bin/_postinstall.py
> +			"listen" not in traffic_ops_golang or
I get a stack trace running `./postinstall.test.sh`:

```python
INFO:root:Starting postinstall
INFO:root:Debug is on
INFO:root:Running in automatic mode
INFO:root:Using input file /tmp/tmp.DTjLbmAc4k/defaults.json
INFO:root:File sanity check complete - found 0 differences
INFO:root:===========/opt/traffic_ops/app/conf/production/database.conf===========
INFO:root:Database configuration has been saved
INFO:root:===========/opt/traffic_ops/app/conf/production/tv.conf===========
INFO:root:Database configuration has been saved
INFO:root:===========/opt/traffic_ops/app/conf/ldap.conf===========
INFO:root:===========/opt/traffic_ops/install/data/json/users.json===========
INFO:root:===========/opt/traffic_ops/install/data/json/openssl_configuration.json===========
INFO:root:===========/opt/traffic_ops/install/data/json/profiles.json===========
INFO:root:Installing SSL Certificates
INFO:root:
        We're now running a script to generate a self signed X509 SSL certificate
INFO:root:Postinstall SSL Certificate Creation
INFO:root:The server key has been generated
INFO:root:Generating an RSA Private Server Key
INFO:root:Creating a Certificate Signing Request (CSR)
INFO:root:The Certificate Signing Request has been generated
INFO:root:Removing the pass phrase from the server key
INFO:root:The pass phrase has been removed from the server key
INFO:root:Generating a Self-signed certificate
INFO:root:A server key and self signed certificate has been generated
INFO:root:Installing a server key and certificate
INFO:root:The private key has been installed
INFO:root:Installing self signed certificate
INFO:root:Saving the self signed csr
INFO:root:
        The self signed certificate has now been installed.

        You may obtain a certificate signed by a Certificate Authority using the
        server.csr file saved in the current directory.  Once you have obtained
        a signed certificate, copy it to /tmp/tmp.DTjLbmAc4k/etc/pki/tls/certs/localhost.crt and
        restart Traffic Ops.
Traceback (most recent call last):
  File "/home/zhoffm468/go/src/github.com/apache/trafficcontrol/traffic_ops/install/bin/_postinstall.py", line 1510, in <module>
    EXIT_CODE = main(
                ^^^^^
  File "/home/zhoffm468/go/src/github.com/apache/trafficcontrol/traffic_ops/install/bin/_postinstall.py", line 1314, in main
    cert_code = setup_certificates(opensslconf, root_dir, ops_user, ops_group)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhoffm468/go/src/github.com/apache/trafficcontrol/traffic_ops/install/bin/_postinstall.py", line 899, in setup_certificates
    "listen" not in traffic_ops_golang or
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'traffic_ops_golang' is not defined
```

2023-05-10 21:27 UTC, rimashah25 commented on .github/actions/to-integration-tests/cdn.json
> +		],
I left the listen field as an array rather than breaking into cert and key since invalidation jobs still uses Config URL that requires scheme

2023-05-10 21:33 UTC, zrhoffman commented on .github/actions/to-integration-tests/cdn.json
> +		],
We don't want to change the `cdn.conf` schema twice, so changing the invalidation jobs to use that is should happen at the same time, unfortunately...

2023-05-16 18:39 UTC, zrhoffman requested changes
Just some unused variables to clean up, besides that it all looks good!

2023-05-16 18:39 UTC, zrhoffman commented on infrastructure/ansible/roles/traffic_ops/templates/cdn.conf.j2
> -   },
With this section removed, these variables are unused and should be removed:

https://github.com/apache/trafficcontrol/blob/c60b07bddcdd6c82697660ab87b41ef888f3bef4/infrastructure/ansible/roles/traffic_ops/defaults/main.yml#L49-L50

https://github.com/apache/trafficcontrol/blob/c60b07bddcdd6c82697660ab87b41ef888f3bef4/infrastructure/ansible/roles/traffic_ops/defaults/main.yml#L67-L78

2023-05-16 18:45 UTC, zrhoffman reviewed
It doesn't have to be in this PR, but in the future, we should remove this postinstall question, since it serves no purpose.

2023-05-16 18:48 UTC, zrhoffman requested changes
Postinstall fails in CDN in a Box. Opening the `ciab-logs` artifact and inspecting `trafficops.log`:

```docker-compose
trafficops_1       | 2023-05-12T18:22:47.518203240Z ++ /opt/traffic_ops/install/bin/postinstall --debug -a --cfile /opt/traffic_ops/install/bin/input.json -n --no-restart-to
trafficops_1       | 2023-05-12T18:22:47.591300943Z INFO:root:Starting postinstall
trafficops_1       | 2023-05-12T18:22:47.591504548Z INFO:root:Debug is on
trafficops_1       | 2023-05-12T18:22:47.591640751Z INFO:root:Running in automatic mode
trafficops_1       | 2023-05-12T18:22:47.591876057Z INFO:root:Using input file /opt/traffic_ops/install/bin/input.json
trafficops_1       | 2023-05-12T18:22:47.592441670Z INFO:root:Adding question 'Port to serve on?' with default answer 443
trafficops_1       | 2023-05-12T18:22:47.592617774Z INFO:root:Adding question 'ldap.conf location?' with default answer /opt/traffic_ops/app/conf/ldap.conf
trafficops_1       | 2023-05-12T18:22:47.592754277Z INFO:root:Adding question 'LDAP server hostname' with default answer 
trafficops_1       | 2023-05-12T18:22:47.592908081Z INFO:root:Adding question 'LDAP Admin Password' with default answer
trafficops_1       | 2023-05-12T18:22:47.593045684Z INFO:root:Adding question 'LDAP Search Query' with default answer 
trafficops_1       | 2023-05-12T18:22:47.593192587Z INFO:root:Adding question 'LDAP Skip TLS verify' with default answer 
trafficops_1       | 2023-05-12T18:22:47.593316090Z INFO:root:Adding question 'LDAP Timeout Seconds' with default answer 
trafficops_1       | 2023-05-12T18:22:47.593457794Z INFO:root:File sanity check complete - found 7 differences
trafficops_1       | 2023-05-12T18:22:47.593586597Z INFO:root:===========/opt/traffic_ops/app/conf/production/database.conf===========
trafficops_1       | 2023-05-12T18:22:47.594050207Z INFO:root:Database configuration has been saved
trafficops_1       | 2023-05-12T18:22:47.594551519Z INFO:root:===========/opt/traffic_ops/app/conf/production/tv.conf===========
trafficops_1       | 2023-05-12T18:22:47.594916027Z INFO:root:Database configuration has been saved
trafficops_1       | 2023-05-12T18:22:47.595348438Z INFO:root:Not setting up ldap
trafficops_1       | 2023-05-12T18:22:47.595526342Z INFO:root:===========/opt/traffic_ops/install/data/json/users.json===========
trafficops_1       | 2023-05-12T18:22:47.679911908Z INFO:root:===========/opt/traffic_ops/install/data/json/openssl_configuration.json===========
trafficops_1       | 2023-05-12T18:22:47.680141114Z INFO:root:===========/opt/traffic_ops/install/data/json/profiles.json===========
trafficops_1       | 2023-05-12T18:22:47.680560923Z INFO:root:Not generating openssl certification
trafficops_1       | 2023-05-12T18:22:47.680722927Z INFO:root:===========/opt/traffic_ops/app/conf/cdn.conf===========
trafficops_1       | 2023-05-12T18:22:47.683847700Z Traceback (most recent call last):
trafficops_1       | 2023-05-12T18:22:47.683861500Z   File "/opt/traffic_ops/install/bin/_postinstall.py", line 994, in generate_cdn_conf
trafficops_1       | 2023-05-12T18:22:47.683865500Z     existing_conf = json.load(conf_file)
trafficops_1       | 2023-05-12T18:22:47.683868800Z   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
trafficops_1       | 2023-05-12T18:22:47.683872300Z     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
trafficops_1       | 2023-05-12T18:22:47.683875301Z   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
trafficops_1       | 2023-05-12T18:22:47.683878501Z     return _default_decoder.decode(s)
trafficops_1       | 2023-05-12T18:22:47.683914801Z   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
trafficops_1       | 2023-05-12T18:22:47.683929002Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
trafficops_1       | 2023-05-12T18:22:47.683932102Z   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
trafficops_1       | 2023-05-12T18:22:47.683935102Z     raise JSONDecodeError("Expecting value", s, err.value) from None
trafficops_1       | 2023-05-12T18:22:47.683938102Z json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
trafficops_1       | 2023-05-12T18:22:47.683941002Z 
trafficops_1       | 2023-05-12T18:22:47.683943702Z The above exception was the direct cause of the following exception:
trafficops_1       | 2023-05-12T18:22:47.683946702Z 
trafficops_1       | 2023-05-12T18:22:47.683949402Z Traceback (most recent call last):
trafficops_1       | 2023-05-12T18:22:47.683952202Z   File "/opt/traffic_ops/install/bin/_postinstall.py", line 1519, in <module>
trafficops_1       | 2023-05-12T18:22:47.683955702Z     ARGS.no_database
trafficops_1       | 2023-05-12T18:22:47.683958602Z   File "/opt/traffic_ops/install/bin/_postinstall.py", line 1322, in main
trafficops_1       | 2023-05-12T18:22:47.683961603Z     postgresTV = generate_cdn_conf(user_input[CDN_CONF_FILE], CDN_CONF_FILE, automatic, root_dir)
trafficops_1       | 2023-05-12T18:22:47.683964503Z   File "/opt/traffic_ops/install/bin/_postinstall.py", line 998, in generate_cdn_conf
trafficops_1       | 2023-05-12T18:22:47.683967503Z     raise exception
trafficops_1       | 2023-05-12T18:22:47.683970303Z ValueError: invalid existing cdn.config at /opt/traffic_ops/app/conf/cdn.conf: Expecting value: line 2 column 1 (char 1)
trafficops_1       | 2023-05-12T18:22:47.690645158Z Error on line 38 of /opt/traffic_ops/install/bin/postinstall
trafficops_1       | 2023-05-12T18:22:47.691045368Z +++ echo 'Error on line 216 of /run-go.sh'
trafficops_1       | 2023-05-12T18:22:47.691131170Z Error on line 216 of /run-go.sh
trafficops_1       | 2023-05-12T18:22:47.691199471Z +++ exit 1
```

2023-05-19 05:05 UTC, rimashah25 commented
> It doesn't have to be in this PR, but in the future, we should remove this postinstall question, since it serves no purpose.

What question is it?

2023-05-19 05:22 UTC, zrhoffman commented
> > It doesn't have to be in this PR, but in the future, we should remove this postinstall question, since it serves no purpose.
> 
> What question is it?

Whoops, meant to link the *Number of workers?* question

https://github.com/apache/trafficcontrol/blob/7390acc5769838aff9d588ac55f96ccf03f2f464/traffic_ops/install/bin/_postinstall.py#L246-L246

2023-05-19 05:29 UTC, rimashah25 commented
> Expecting value: line 2 column 1 (char 1)

I looked at the traceback and the line (998) where the error is being generated is not informative
``` Expecting value: line 2 column 1 (char 1)```

2023-05-19 18:03 UTC, zrhoffman commented
> > Expecting value: line 2 column 1 (char 1)
> 
> I looked at the traceback and the line (998) where the error is being generated and it is not informative. ` Expecting value: line 2 column 1 (char 1)`

The error is happening at the top line of the stack trace:

```
  File "/opt/traffic_ops/install/bin/_postinstall.py", line 994, in generate_cdn_conf
    existing_conf = json.load(conf_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

so `_postinstall.py", line 994, in generate_cdn_conf`

https://github.com/apache/trafficcontrol/blob/7390acc5769838aff9d588ac55f96ccf03f2f464/traffic_ops/install/bin/_postinstall.py#L994

2023-05-31 20:24 UTC, zrhoffman approved these changes
Looks great!

2023-05-31 20:24 UTC, merged