Added API Contract test case for servers endpoint and refactored existing ones.
apache/trafficcontrol pull request #7523
Opened 2023-05-15 20:33 UTC by gokulakrishnansvm

- Added Api contract test case for server endpoint.
- Refactored code for all existing Api contract test cases, Used Json schema validation for validating Keys and data types of values in the test case.
- Replaced response_template.json file with json schema formats.
- Refactored all fixtures(post_data) in conftest, Added common method to verfiy response template and added common methods for get and post requests.
- Moved request_template.json , response_template.json and to_data.json to folder named data.
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Ops Test

## What is the best way to verify this PR?

Step 1 : Follow steps from README file(traffic_ops/testing/api_contract) to run api-contract-tests.

Step 2 : To execute servers API Contract Testcase , navigate to traffic_ops/testing/api_contract/v4
pytest --to-user Username --to-password Password --to-url URL --config Config Path --request-template Request template --response-template Response template test_servers.py

Note: Config, Request template and response template paths are optional. 

## PR submission checklist
- [x] This PR has tests 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

2023-05-15 20:57 UTC, TerekhovaKate commented on traffic_ops/testing/api_contract/v4/conftest.py
> +		shortname = phys_locations["shortName"]
shortName = phys_locations["shortName"]
 	shortname = phys_locations["shortName"]
 	please check name 
 	short_name is recomended

2023-05-15 21:31 UTC, ericholguin commented on traffic_control/clients/python/trafficops/tosession.py
> +	@api_request('post', 'phys_locations', ('3.0', '4.0', '4.1', '5.0'))
Please re-add 3.1

2023-05-16 18:49 UTC, TerekhovaKate requested changes

2023-05-16 18:49 UTC, TerekhovaKate commented on traffic_ops/testing/api_contract/v4/conftest.py
> +	if api_response:
Validate api_data before returning: Currently, the code assumes that if api_response is not empty, the first element of api_response is the desired data. However, it doesn’t verify if it’s a valid data object. Consider adding validation for api_data before returning it.

2023-05-17 19:33 UTC, TerekhovaKate approved these changes
Nice work !

2023-05-17 20:27 UTC, merged