Add comments field
apache/trafficcontrol pull request #7845
Opened 2023-10-23 10:49 UTC by ntheanh201

Closes: #7456 

Add field "comment" to parameter

## Which Traffic Control components are affected by this PR?
- Traffic Ops
- Traffic Portal

## What is the best way to verify this PR?
- Provisioning CDN in a Box, select Configure/Parameters, 1 more columns "comment" should show
- Create/Update Parameters with "comment"

## If this is a bugfix, which Traffic Control versions contained the bug?

## PR submission checklist
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

2023-11-01 17:39 UTC, ocket8888 commented
I am -1 on this idea. The promise of a comments field being used only for humans' benefits has been repeatedly broken on other objects, and a Parameter ought to be too small to express anything complex enough to require a comment. In fact, Parameters as objects should not even exist in their own right, IMO, and - especially now that Profile layering is possible - instead just be properties of Profiles. In some respects, they are represented that way already, and that means that this amounts to, in those cases, having an unbounded number of free-form text fields on a collection of free-form text fields on a Profile.

2023-11-02 07:26 UTC, ntheanh201 commented
> at way already, and that means that this amounts to, in those cases, having an unbounded number of free-form text fields on a collection of free-form text fields on a Profile.

IMO I still need a description of some special parameters that are required for the Profile

2023-11-10 02:39 UTC, ocket8888 commented
Any Parameter that is required for a Profile of some given type ought not to be optionally provided by the data model; instead it should be a required property of a Profile.

2023-11-29 17:05 UTC, mitchell852 commented
@ntheanh201 - can you make it optional to show this field in traffic portal? for example, add a config setting like parameter.comment.show = false to the [traffic portal properties file](https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/traffic_portal_properties.json) and key off that in the UI.

2023-12-01 02:57 UTC, ntheanh201 commented
> @ntheanh201 - can you make it optional to show this comment field in traffic portal? for example, add a config setting like parameter.comment.show = false to the [traffic portal properties file](https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/traffic_portal_properties.json) and key off that in the UI.

Updated like this, please take a look!

2023-12-06 04:16 UTC, ocket8888 commented
I'm still -1 on this idea. Adding tech debt doesn't seem like a good way to resolve tech debt.

2023-12-18 18:39 UTC, kdamichie requested changes

2023-12-20 20:34 UTC, kdamichie approved these changes
Looks good.  Comment field is present under parameters

2024-01-03 16:14 UTC, kdamichie commented
@ntheanh201 ^

2024-01-04 01:15 UTC, ntheanh201 commented
> Sorry to amend my response. But can you verify this test failure. Looks like it needs a test update.

It has not failed because of this code, this failure is related to the integration tests themselves being broken, you can see some other commits

2024-01-04 16:03 UTC, kdamichie approved these changes
Approved

2024-02-01 17:01 UTC, zrhoffman commented
@ocket8888 Responded in https://github.com/apache/trafficcontrol/issues/7456#issuecomment-1917912002 because a PR is not the place to discuss the validity of an Issue. With no response after a week, I'll assume you agree and will merge

2024-10-18 03:49 UTC, ntheanh201 commented
@zrhoffman can you merge?

2024-10-18 03:57 UTC, zrhoffman commented
> @zrhoffman can you merge?

If we can verify that no committers are against #7845 being merged, yes. I'll clarify in Issue #7456 :)

2024-10-18 20:35 UTC, zrhoffman requested changes
Just a small change needed with the migration timestamp, then it should be good to merge. Thanks!

2024-10-18 20:35 UTC, zrhoffman commented on traffic_ops/app/db/migrations/2023121910512261_add_comment_parameter.down.sql
> +/*
The timestamp on this migration, `2023121910512261`, is 10 months old. Would you please give it a more recent timestamp (for example, `2024101800000000`)?

2024-10-18 20:35 UTC, zrhoffman commented on traffic_ops/app/db/migrations/2023121910512261_add_comment_parameter.up.sql
> +/*
Same thing here, the timestamp `2023121910512261` is from last year and should be replaced with something more recent.

2024-12-18 08:11 UTC, ntheanh201 commented
@zrhoffman I updated it

2024-12-18 08:28 UTC, zrhoffman approved these changes
Look great, thanks a lot! :)

2024-12-18 09:25 UTC, merged